const macbookPage=(req,res)=>{
    res.send([
    {
        id:1,
        title:"macbook",
        star:"⭐⭐⭐⭐⭐",
        cost:"5050$",
        image:"https://tse1.mm.bing.net/th?id=OIP.rMgGd0dnZXVUr-LW0Aaw2QHaHa&pid=Api&P=0" 
    },
    {
        id:2,
        title:"macbook",
        star:"⭐⭐⭐⭐⭐",
        cost:"5050$",
        image:"https://tse1.mm.bing.net/th?id=OIP.rMgGd0dnZXVUr-LW0Aaw2QHaHa&pid=Api&P=0" 
    },
    {
        id:3,
        title:"macbook",
        star:"⭐⭐⭐⭐⭐",
        cost:"5050$",
        image:"https://tse1.mm.bing.net/th?id=OIP.rMgGd0dnZXVUr-LW0Aaw2QHaHa&pid=Api&P=0" 
    },{
        id:4,
        title:"macbook",
        star:"⭐⭐⭐⭐⭐",
        cost:"5050$",
        image:"https://tse1.mm.bing.net/th?id=OIP.rMgGd0dnZXVUr-LW0Aaw2QHaHa&pid=Api&P=0" 
    },{
        id:5,
        title:"macbook",
        star:"⭐⭐⭐⭐⭐",
        cost:"5050$",
        image:"https://tse1.mm.bing.net/th?id=OIP.rMgGd0dnZXVUr-LW0Aaw2QHaHa&pid=Api&P=0" 
    },{
        id:6,
        title:"macbook",
        star:"⭐⭐⭐⭐⭐",
        cost:"5050$",
        image:"https://tse1.mm.bing.net/th?id=OIP.rMgGd0dnZXVUr-LW0Aaw2QHaHa&pid=Api&P=0" 
    },
    {
        id:7,
        title:"macbook",
        star:"⭐⭐⭐⭐⭐",
        cost:"5050$",
        image:"https://tse1.mm.bing.net/th?id=OIP.rMgGd0dnZXVUr-LW0Aaw2QHaHa&pid=Api&P=0" 
    },{
        id:8,
        title:"macbook",
        star:"⭐⭐⭐⭐⭐",
        cost:"5050$",
        image:"https://tse1.mm.bing.net/th?id=OIP.rMgGd0dnZXVUr-LW0Aaw2QHaHa&pid=Api&P=0" 
    },
    {
        id:9,
        title:"macbook",
        star:"⭐⭐⭐⭐⭐",
        cost:"5050$",
        image:"https://tse1.mm.bing.net/th?id=OIP.rMgGd0dnZXVUr-LW0Aaw2QHaHa&pid=Api&P=0" 
    },
    {
        id:10,
        title:"macbook",
        star:"⭐⭐⭐⭐⭐",
        cost:"5050$",
        image:"https://tse1.mm.bing.net/th?id=OIP.rMgGd0dnZXVUr-LW0Aaw2QHaHa&pid=Api&P=0" 
    },
    {
        id:11,
        title:"macbook",
        star:"⭐⭐⭐⭐⭐",
        cost:"5050$",
        image:"https://tse1.mm.bing.net/th?id=OIP.rMgGd0dnZXVUr-LW0Aaw2QHaHa&pid=Api&P=0" 
    },{
        id:12,
        title:"macbook",
        star:"⭐⭐⭐⭐⭐",
        cost:"5050$",
        image:"https://tse1.mm.bing.net/th?id=OIP.rMgGd0dnZXVUr-LW0Aaw2QHaHa&pid=Api&P=0" 
    }
])
}
module.exports.macbookPageData=macbookPage